### ISSUE TITLE
(question): Fresh Project Creation

### ISSUE THREAD

**Issue by ilan-gold** [SunDoge/dlpark#14]
In your repo, checked out locally, everything works, but when I copy the `with_pyo3` example over into another folder, I get 

```
the trait bound `dlpark::ManagerCtx<Vec<f32>>: OkWrap<dlpark::ManagerCtx<Vec<f32>>>` is not satisfied
the trait `OkWrap<T>` is implemented for `Result<T, E>`
required for `dlpark::ManagerCtx<Vec<f32>>` to implement `OkWrap<dlpark::ManagerCtx<Vec<f32>>>`
```

on `#[pyfunction]` with `ManagerCtx` as a returned object (and a different error when it is an argument).  In my own project (which I'm really interested in), I as well as a similar one when I try returning `PyResult<ManagerContext<Vec<u8>>>` in my own `#[pymethods]` block.  Briefly here's what I took from this repo as an example into its own project as a reproducer of this behavior:

`Cargo.toml`
```toml
[package]
name = "with_pyo3"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["cdylib"]
name = "mylib"


[dependencies]
pyo3 = { version = "0.21.0", features = ["extension-module"] }
dlpark = "0.4.1"
```

`src/lib.rs`
```rust
use dlpark::prelude::*;
use pyo3::{prelude::*, types::PyDict};

#[pyfunction]
pub fn add(left: usize, right: usize) -> usize {
    left + right
}

#[pyfunction] // error here
pub fn arange(n: usize) -> ManagerCtx<Vec<f32>> {
    let v: Vec<f32> = (0..n).map(|x| x as f32).collect();
    ManagerCtx::new(v)
}

#[pyfunction]
pub fn tensordict(py: Python<'_>) -> PyResult<Bound<'_, PyDict>> {
    let dic = PyDict::new_bound(py);
    let v1: Vec<f32> = vec![1.0; 10];
    let v2: Vec<u8> = vec![2; 10];
    dic.set_item("v1", ManagerCtx::new(v1).into_py(py))?;
    dic.set_item("v2", ManagerCtx::new(v2).into_py(py))?;
    Ok(dic)
}

#[pyfunction] // error here as well
pub fn print_tensor(tensor: ManagedTensor) {
    dbg!(
        tensor.shape(),
        tensor.strides(),
        tensor.dtype(),
        tensor.device()
    );
    assert!(tensor.dtype() == DataType::F32);
    dbg!(tensor.as_slice::<f32>());
}

#[pymodule]
fn mylib(_py: Python<'_>, m: &Bound<'_, PyModule>) -> PyResult<()> {
    m.add_function(wrap_pyfunction!(add, m)?)?;
    m.add_function(wrap_pyfunction!(arange, m)?)?;
    m.add_function(wrap_pyfunction!(tensordict, m)?)?;
    m.add_function(wrap_pyfunction!(print_tensor, m)?)?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn it_works() {
        let result = add(2, 2);
        assert_eq!(result, 4);
    }
}
